# -*- coding: utf-8 -*-
"""sandbox.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1caYyn7hpCDbXe7eRCSKT6S8jB_A7FFv6
"""

!gcloud auth application-default login

import pandas as pd
from google.cloud import bigquery
import os

df = pd.read_csv("/content/dummy.txt")

df.head()

project_id = "allennlp"
json_path = "/content/.config/application_default_credentials.json"
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]=json_path
bq_client = bigquery.Client(project=project_id)

dataset_id = "jposada_explore"
table_id = "dummy_table"
bq_client.load_table_from_dataframe(dataframe=df,
                                    destination=f"{project_id}.{dataset_id}.{table_id}")



